---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jay.
--- DateTime: 2025/5/20 16:05
---
-- 这里的KEYS[1]就是传入锁的key
-- 这里的ARGV[1]就是线程标识
-- 比较锁中的线程标识与线程标识是否一致
if (redis.call('get', KEYS[1]) == ARGV[1]) then
    -- 一致则释放锁
    return redis.call('del', KEYS[1])
end
return 0